name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set2
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    
    - name: Deploying ansible on vm backup
      run: |
        sudo apt update -y
        sudo apt-get install openssh-server
        sudo apt -y install sshpass
        sudo apt -y install mysql-client-core-8.0
        sudo apt -y install mysql-server
        sudo apt -y install ansible
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        sudo systemctl enable ssh --now
        ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
